kind: Pod
apiVersion: v1
metadata:
  annotations:
    pod.alpha.kubernetes.io/isolation-api: '{
        "cpu-pinning": "0-1"
    }'
  name: stress-with-pinning
  labels:
    app: example
spec:
  containers:
  - name: stress
    image: progrium/stress
    args:
    - --cpu
    - "2"

